### ISSUE TITLE
Make it work with .actr files

### ISSUE THREAD

**Issue by heldmoritz** [fmagin/vscode-act-r#1]
Hi, thanks for your contribution! I am mainly working with .actr files as they are read into the Java version of ACT-R. Is it feasable to adapt your plugin to work with this file extension as well? Not knowing anything about coding plugins, I imagine it to be fairly straight foward as the syntax is the same.

best,
m

Edit: Now that I'm trying it with lisp files, it does indeed not seem to work with many files

**Comment by fmagin** [comment]
Hey, thanks for the feedback :)

"Suppporting" `.actr` files like `.lisp` should be a trivial change if the syntax is the same and I just published an update that activates the extension on `.actr` files.

But overall this extension is still more of a proof of concept, and only really works for the specific assignment I had to do. ACT-R sadly doesn't have a properly specified and machine readable formal language grammar, so all of this had to be done by reading the ACT-R manual and translating the grammar which was quite painstaking. It took me around two days just to get this far, and it was just a small fraction of the possible ACT-R functions.

I have a few ideas that might make it possible to cover the entirety of the ACT-R language if someone can provide me the source file used to generate the ACT-R manual PDF, but I'd still expect this to take a few weeks of full time effort.

**Comment by heldmoritz** [comment]
I do not have the source file used to generate the ACT-R manual PDF, however, I may be able to provide something that is useful. The Java version of ACT-R runs on an applet that stylizes the model code (see below). How exactly this works, you can find under Document.java. Hope this helps. You can find the Java version here: https://www.cs.drexel.edu/~salvucci/cog/act-r/
![image](https://user-images.githubusercontent.com/52459329/91266760-303fd880-e772-11ea-9c3e-222029322591.png)

**Comment by fmagin** [comment]
I might look into the Java highlighting, but at first glance it looks a lot more promitive than my approach. But at least it's consistent, so I might integrate it some day as an alternative.

For now though: Does current version of the plugin successfully activate for `.actr` files for you? If yes I will be closing this issue.

**Comment by heldmoritz** [comment]
Unfortunately, I cannot tell as the syntax is slightly different and thus nothing is highlighted.

**Comment by fmagin** [comment]
In what way is the syntax for `.actr` files different? If you can provide me an example file, I can look into it.

**Comment by heldmoritz** [comment]
A few small things... e.g. the model doesn't need to be defined. 

Example file: https://www.cs.drexel.edu/~salvucci/cog/act-r/projects/driving.zip

**Comment by fmagin** [comment]
Would you feel comfortable with setting up a test environment with a specific branch of the repo? Otherwise I have to release the plugin every time to get feedback from you, which is limiting but doable. It should just involve cloning the repo, opening it with VS Code and hitting F5 to start a Develop instance of VS Code which then has all the changes. The branch is https://github.com/fmagin/vscode-act-r/tree/dev

Otherwise you can give me a more specific list of the "few small things". Highlighting the procedures outside a model definition was a simple change, other things might be too.

**Comment by fmagin** [comment]
Preview of the current version:
![image](https://user-images.githubusercontent.com/8415354/92101296-36226300-eddd-11ea-83cd-09851d21cb1f.png)

`!bind!` isn't handled yet IIRC, so implementing that might be another large improvement. Same for `!eval!`. Looking into how hard this is now.

**Comment by fmagin** [comment]
Ok, I was confident enough that the changes I made are good enough that I might as well publish them now. The new version `0.2.0` should be available in the VS Code Marketplace any minute.

**Comment by fmagin** [comment]
If you have any further things that you consider relevant for working with the `.actr` kind of files, you can just reopen this issue with a specific example and I will look into it. Closing this for now, because to the best of my judgement based on the `Driving.actr` example the support for `.actr` files is now roughly on par with the regular files/format.

**Comment by heldmoritz** [comment]
Excellent work, thanks! Works very well for my purposes and makes actr files a lot easier to work with. 
If you are open to feedback still, I have two (small) things: If I assign a variable to a slot, both variable and slot have the same colour. This is somewhat unintuitive as I would presume that same colour = same thing. 
Example: make oldid greenish or red like rehearse0 in the example below.
![image](https://user-images.githubusercontent.com/52459329/92208093-bf43a380-ee8a-11ea-81f3-9d1662f73b2d.png)

Also I don't see the need to differentiate between numerical slot values and strings, but I might be wrong here. Is there a specific reason you decided to do this?

Same goes for module calls and chunk types. I would differentiate these by giving chunk type a different colour.
Example: make nback a new colour, perhaps same as slot values?
![image](https://user-images.githubusercontent.com/52459329/92208220-0c277a00-ee8b-11ea-8d08-bc8ce0540478.png)

Other than that, great work!

Edit: One more tiny thing: one semi-colon is acceptable to indicate a comment (you require two)

**Comment by fmagin** [comment]
I definitely appreciate any feedback, I only used ACT-R for a few hours in total.

#### VS Code language support sketch

I'll try to quickly sketch out the process of syntax highlighting:
The plugin only provides a special form of grammar according to which the file is parsed, tokenized and the tokens are assigned names of a certain form, e.g. `string.unquoted`, `keyword`., `entitiy.name.type`, etc.
VS Code itself will then, based on your theme and other settings, color the tokens that have certain names in the configured colors. You can use the [scope inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) to see this.

There will basically be two cases:

#### 1. The name assigned is plain wrong,
![image](https://user-images.githubusercontent.com/8415354/92232043-1ad35880-eeae-11ea-8dc9-c99ad81f1334.png)

The syntax highlighting is more of a lucky accident that I don't even fully understand, but still results in reasonable coloring.

`is-car-stable` is not really an unquoted string, but a function name in an expression that is evaluated. Technically the entirety of an ACT-R lisp file is an unquoted string that is then passed to a lisp macro in the original implementation, but this is pointless for syntax highlighting of the DSL that is actually implemented inside the macro. `=` is recognized as a keyword and `na` as a variable which is correct again.


#### 2. The names and scopes are my best attempt to reasonably reflect the ACT-R semantics

![image](https://user-images.githubusercontent.com/8415354/92233213-29227400-eeb0-11ea-92df-8cb629d7761c.png)


This `visual-location` is `entity.name.type.chunk`. `entity.name.type` is a name that is defined by VS Code meaning that this token is the name of a type. The `chunk` is for debugging and for more specific color configuration. The `goal` inside `=goal>` is `entity.name.type.buffer`, so by default it will be colored based on `entity.name.type`

Because the process of writing this plugin and language definition was how I learned the ACT-R semantics in the first place, there can also be errors as part of this.


### Integrating your feedback

The recommended naming convention that themes use is described in https://macromates.com/manual/en/language_grammars#naming_conventions .

Now to your concrete feedback:

> If I assign a variable to a slot, both variable and slot have the same color.

If I understand you correctly, this depends on your theme and isn't actually the case with my theme ("Better Solarized Light"). 
![image](https://user-images.githubusercontent.com/8415354/92234655-b666c800-eeb2-11ea-9e4b-cc981907d3cc.png)

`distance` is assigned the name `variable.parameter` and `nd` is assigned the name`variable`. Some themes color those differently (like mine), while the VS Code default doesn't. I am not sure if I want to workaround the VS Code default theme here, but if there is a better name for those tokens that results in better coloring overall I am open to it.

> make oldid greenish or red like rehearse0

that seems wrong to me though. `oldid` is the name of a variable and that is not the same as an arbitrary string like `rehearse0` or types (which are greenish in the default theme). Am I misunderstanding the general interpretation of the ACT-R syntax here? 

> differentiate between numerical slot values and strings

That might be a leftover from the Lisp grammar I based mine on. In Lisp numerical values and strings are obviously not the same, but IIRC in ACT-R numerals are just symbols anyway. I don't see harm in it though.


So overall there is actually a lot of nuances to discuss in your feedback. I'd really like to know your view on the name choices. The color choices mostly derive from the names, so some [tweaking can be done](https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting) for the name->color mapping (i.e. the theme), but the names should mostly reflect the ACT-R semantics itself.

**Comment by heldmoritz** [comment]
> This visual-location is entity.name.type.chunk. entity.name.type is a name that is defined by VS Code meaning that this token is the name of a type. The chunk is for debugging and for more specific color configuration. The goal inside =goal> is entity.name.type.buffer, **so by default it will be colored based on entity.name.type**

IMO this is what is problematic. `=goal>` describes the buffer that you'd like to access while `isa drive` is the description of the chunk type that is placed or changed in the buffer. It is a bit more unintuitive for the visual location buffer because the names are the same in the example but the principle is the same. `=visual-location>` is the name of the buffer, while `isa visual-location `is the chunk type. You can demonstrate this by changing `isa visual-location` to basically anything you would like, however, if you try to change `=visual-location>`, you will get an error as there is likely no such buffer to access. Making these the same colour suggests similarity in my view which is not correct. These are two different things.

--

It's weird that slots and values have the same colour in any theme but if it's specific to mine, then I guess I'll have to change it.

> that seems wrong to me though. oldid is the name of a variable and that is not the same as an arbitrary string like rehearse0 or types (which are greenish in the default theme). Am I misunderstanding the general interpretation of the ACT-R syntax here?

I guess that depends on general coding conventions but I'm still not sure if differentiating between variables and strings makes sense. Both of these are essentially values that you assign to a specific slot. My thinking is: Make the slot a specific colour and the slot content a different colour. Differentiating between different types of values for a slot is unnecessary in my view but I might be too used to the default ACT-R highlighting...
